# Generated by Django 4.2.2 on 2023-07-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
        ('authapp', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_tours',
            field=models.ManyToManyField(blank=True, to='mainapp.tour'),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
